# Generated by Django 4.1.2 on 2022-11-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("pick_time", models.DateTimeField()),
                ("drop_time", models.DateTimeField()),
                ("cost", models.FloatField()),
                ("no_of_vehicle", models.IntegerField()),
                ("charge", models.IntegerField()),
            ],
            options={"db_table": "booking",},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
                ("job", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("phone_no", models.CharField(max_length=20)),
            ],
            options={"db_table": "employee",},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "loc_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("cars_available", models.IntegerField(blank=True, null=True)),
                ("bikes_available", models.IntegerField(blank=True, null=True)),
                ("phone_no", models.CharField(max_length=20)),
            ],
            options={"db_table": "location",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("phone_no", models.CharField(max_length=20)),
                ("user_type", models.BooleanField()),
                ("wallet", models.FloatField(default=0)),
            ],
            options={"db_table": "user",},
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("vehicle_type", models.BooleanField()),
                ("booking_status", models.BooleanField(default=False)),
                ("repair_status", models.BooleanField(default=False)),
                (
                    "repair_desc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("costhr", models.FloatField()),
                ("charge", models.FloatField()),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.location",
                    ),
                ),
            ],
            options={"db_table": "vehicle",},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "billing_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("payment_method", models.CharField(max_length=20)),
                ("amount", models.IntegerField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer.user",
                    ),
                ),
            ],
            options={"db_table": "payment",},
        ),
        migrations.AddField(
            model_name="booking",
            name="drop_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drop",
                to="customer.location",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pick_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pick",
                to="customer.location",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.user",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.vehicle",
            ),
        ),
    ]
